# -*- coding: utf-8 -*-
"""Project_(2)_Tic_Tac_Toe_(1) (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LIsOWhTI0TtijS78tjRslxRj7zkmWFTK

<a href="https://www.zero-grad.com/">
         <img alt="Zero Grad" src="https://lh3.googleusercontent.com/oEMY-qk_B2HW_Fponz1a3u1fLfo3NpO0VFjQKnVW8fH0v93NAWala5Kgp0nN2ubiyZdEMpwhv3Ynv7bXsB0RZ28YfEd_ZlRum75OHEu0-z7XwHfcD3sin7_SORLzg1gz52MsxD3b1WbxQWX1RdR4HP3jpbJTOuCiddl92UBcQH_x-Llx7_XuZuwb9ekN9vYnKsw6U1yL2df4IVrJEDySttzab9qlHvMO7sSekgS64jPVAmATjqXqlvrwM026dhrad-7nX-hfr2uKlUGPuo9xKzVo4EhbUP1-pKBQNPNHO6P0KcReg3NxbtKmWXRyg9LPX0xO-wwXWt9GhCcPXFV_BoY5eQXabCjR3mlr9SO01VgWplas-XF4337_JOm-bVkiaQjQca_N4Gg0hy26TvIGRnHEMIPSgudYPqhMnatoN4xAC715rP82r1svC0_qadXMZHu6D40YqWnY9ZE-iujr2p1_CetxmG-uY94UATy7o-SnxuPchG4QfZkiUgRMr8xNg86bQMuBxbCS_lOyVMwfqwbt2IunlDcZ8yyN_3SJFzFHuFOOjQolgGQrytI0mP1oTwba7je0RtBtCuTck1UCMMsZvMnJhCtWgMmuLoYTkSCzxMXbz0T3L2AClDouA_3dwM7z1gdm8Gq4v06T1KWFUs1adGNH5fuj-pUHEfW4drzzXgolPH5SehqhaNsqdMttCPUzNPIIEjwfULyQi7nlP-w-qydK82mdhdmjQhrprfoGtsPckJkI1Tur60uZI7nLkES5cE3tQrGualSNArRkkU8KN4tStZ0CkmqZNkAlMbfAJSYBD7tDxhGSg922AdLevSLJMTUyg6KuHoY30r7zH1Z8fE0R8aFZL2LJl54OU_tkXEdlFlSnZTOdB-PVTj-yagpt99SetLnQIX5SS_Vxc0BNPKjUZG0oEHYbIxkbZN1O7Rg78xe-thytngS0byfuaeP2X4NYjg29FIffnn72bAUs9Ii0N2mOpABLg1uQMN4MyAa1Mbd_=w1300-h200-no?authuser=1" >
      </a>

# Tic Tac Toe Project Description

**`(1) Create Empty board (3x3):`**

  `1  2  3`

  `4 5 6`

  `7 8 9`

 **`(2) Show Board`**

 **`(3) Set Players Randomly ('X', 'O')`**

 **`(4) Take Input from Player`**

 **`(5) Check Full Board >> Draw`**

 **`(6) Check if Someone wins >> Finish`**

# Template

## Empty Board
"""

def create_empty_board():
    board = [['1', '2', '3'], ['4', '5', '6'], ['7', '8', '9']]

    for i in board:
        for j in i:
            print(j, end="\t")
        print('\n')
    return board

#create_empty_board()

"""## Show Board"""

def show_board(board):
    for i in board:
        for j in i:
            print(j, end="\t")
        print('\n')

#board = [[1,2,3],[4,'X',6],[7,8,9]]
#show_board(board)

"""## Set Players"""

import random
def set_players():
    player=random.choice(('X', 'O'))
    if player == 'X':
        return ('X', 'O')
    else :
        return ('O', 'X')

#set_players()

"""## Take Input"""

def take_input(board, player):
        num=int(input("Please Enter a number between 1,9 represents an empty position:    "))

        if num>=1 and num<=9:
            row = (num - 1) // 3
            col = (num - 1) % 3

            if board[row][col].isdigit():
                board[row][col] = player
            else:
                print("invalid choice")

        show_board(board)

board = [['1','2','3'],['4','X','6'],['7','8','9']]
player ='O'
player_input = '8'
#take_input(board, player)

"""## Check Full Board"""

# how to Check Full Board
def check_full_board(board):
    for i in board:
        for j in i:
            if j.lower() =='o' or j.lower()=='x':
                continue
            else :
                return False


    return True

board = [['o','x','x'],['o','X','o'],['x','o','x']]
#check_full_board(board)

board = [['o','x','x'],['4','X','o'],['x','o','x']]
#check_full_board(board)

"""## Check Win

"""

def check_win(board):
    for row in board:
        if row[0] == row[1] == row[2] :
            return True
    for col in range(3):
        if board[0][col] == board[1][col] == board[2][col] :
            return True
    # two diagonals
    if board[0][0] == board[1][1] == board[2][2] :
        return True
    if board[0][2] == board[1][1] == board[2][0] :
        return True
    return False

board = [['o','x','x'],['o','o','x'],['x','o','x']]
#show_board(board)
check_win(board)

board = [['o','x','o'],['o','o','x'],['x','o','x']]
#show_board(board)
#check_win(board)

"""## Let's Play"""

def play():
    player1, player2 = set_players()
    board = create_empty_board()

    while True:
        print(f"Player {player1} turn ")
        take_input(board, player1)

        if check_win(board):
            print(f"Player {player1} wins!")
            break
        if check_full_board(board):
            print("It's a draw!")
            break

        print(f"Player {player2} turn ")
        take_input(board, player2)

        if check_win(board):
            print(f"Player {player2} wins!")
            break
        if check_full_board(board):
            print("It's a draw!")
            break

play()